export enum UnitType {
  MONEY_PARTITION_BILL_DATA = '0x00',
  MONEY_PARTITION_FEE_CREDIT_RECORD = '0x0F',
  TOKEN_PARTITION_FUNGIBLE_TOKEN_TYPE = '0x20',
  TOKEN_PARTITION_FUNGIBLE_TOKEN = '0x21',
  TOKEN_PARTITION_NON_FUNGIBLE_TOKEN_TYPE = '0x22',
  TOKEN_PARTITION_NON_FUNGIBLE_TOKEN = '0x23',
  TOKEN_PARTITION_FEE_CREDIT_RECORD = '0x2F',
}
